[package]
name = "reversi"
version = "0.1.2"
authors = ["JPNYKW <jpnykw@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.69.0"
freetype-rs = "0.23.0"
find_folder = "0.3.0"
